### ISSUE TITLE
Only showing CPU frequency (AMD Ryzen 7 4800H)

### ISSUE THREAD

**Issue by julenpardo** [ocerman/zenmonitor#27] opened 2020-06-04 17:00 UTC
Hello,

I've installed both zenpower and zenmonitor AUR packages. Everything was fine, but the monitor only shows the core frequencies. I've enabled MSR driver.

![Screenshot_20200604_185518](https://user-images.githubusercontent.com/12843626/83788349-5aaf5780-a695-11ea-8127-cf9329dbcc86.png)

I'm with Manjaro 20.0.2 (kernel 5.6.15-1). Please let me know what more information you'd need.

**Comment by ocerman** [comment] 2020-06-06 14:30
@julenpardo hello, thanks for your report.
The issue is propably with the driver. I have not tested it with new 4000-series CPU.

Can you please post `sensors` output and output of debug data of the driver (you can do it by this bash script: https://gist.github.com/ocerman/6566b00072c8af96a109f65075f2d8b7

**Comment by julenpardo** [comment] 2020-06-06 15:56
Sure, glad to help.

```
❯❯❯ sensors
amdgpu-pci-0500
Adapter: PCI adapter
vddgfx:           N/A  
vddnb:            N/A  
edge:         +49.0°C  (crit =  +0.0°C, hyst =  +0.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +52.0°C  (crit = +115.0°C)

BAT1-acpi-0
Adapter: ACPI interface
in0:           4.01 V  
curr1:         0.00 A  

nvme-pci-0400
Adapter: PCI adapter
Composite:    +42.9°C  (low  = -20.1°C, high = +84.8°C)
                       (crit = +89.8°C)
```

But the output of the bash script is just:

```
Zenpower not found
```

But, I have zenpower installed (AUR package):

```
❯❯❯ pacman -Q zenpower
zenpower-dkms-git 44.ee05fcf-1
```

**Comment by ocerman** [comment] 2020-06-06 17:59
@julenpardo OK, I can confirm that it is indeed a driver issue. The new 4000 series cpus are using new pci ids so that's why the driver is not active.

I will try to update the driver soon and then you should at least get temperatures working. Also after that the script for debug data should be working and hopefully then it would be possible to also get voltage/current monitoring done.

So, as this is a driver issue, I am closing this one and I have opened new driver issue here: ocerman/zenpower#31 . Feel free to post there.

**Closed by ocerman** 2020-06-06 17:59 UTC

**Comment by julenpardo** [comment] 2020-06-06 19:43
That's awesome, many thanks for your work, appreciate it. Will subscribe to that issue.

**Comment by Cheaterman** [comment] 2020-07-11 11:31
Just FYI, if I run zenmonitor as root, I do get power information for my 4800H. :-)
